require('dotenv').config();
const express = require('express');
const axios = require('axios');
const path = require('path');
const { GoogleGenAI } = require('@google/genai');

const app = express();
const PORT = process.env.PORT || 8080;

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY }); 

app.use(express.static(path.join(__dirname, "public")));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

// The OpenWeather API Tool implementation
async function get_current_weather(city) {
  try {
    const apiKey = process.env.API_KEY;
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${apiKey}&units=metric`;
    const response = await axios.get(url);
    const data = response.data;
    return {
      city: data.name,
      temperature: data.main.temp,
      condition: data.weather[0].description,
      humidity: data.main.humidity,
      wind_speed: data.wind.speed
    };
  } catch (error) {
    return { error: "Unable to find weather for this location." };
  }
}

const weatherToolDeclaration = {
  name: 'get_current_weather',
  description: 'Get the current weather for a given city in Celsius.',
  parameters: {
    type: 'OBJECT',
    properties: {
      city: { type: 'STRING', description: 'The name of the city, e.g. London' }
    },
    required: ['city']
  }
};

app.get('/weather', async (req, res) => {
  const query = req.query.query;
  if (!query) return res.json({ error: "Query is required" });

  try {
    const config = {
      systemInstruction: "You are a helpful and smart weather assistant. You use the get_current_weather tool to fetch real-time weather data. Then synthesize a conversational, friendly answer. You MUST provide the temperature, the condition, and any helpful advice based on the weather, such as warning the user if the temperature is too high. Do not use complex markdown, just return plain text.",
      tools: [{ functionDeclarations: [weatherToolDeclaration] }]
    };

    let response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: query,
      config: config
    });

    if (response.functionCalls && response.functionCalls.length > 0) {
      const call = response.functionCalls[0];
      if (call.name === 'get_current_weather') {
        const weatherData = await get_current_weather(call.args.city);
        
        const history = [
            { role: 'user', parts: [{ text: query }] },
            response.candidates[0].content, // The tool call generated by the model
            { 
                role: 'user', 
                parts: [{ 
                    functionResponse: { name: call.name, response: weatherData } 
                }] 
            }
        ];

        response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: history,
            config: config
        });
      }
    }
    
    res.json({ answer: response.text });
  } catch (error) {
    console.error(error);
    res.json({ error: "❌ AI Agent encountered an error processing your request." });
  }
});

app.listen(PORT, () => {
  console.log(`✅ Server running at http://localhost:${PORT}`);
});
